# Generated by Django 3.2.6 on 2021-08-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Online_BookStore', '0005_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldBook',
            fields=[
                ('sold_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Online_BookStore.customer')),
            ],
        ),
    ]
