# Generated by Django 3.2.6 on 2021-11-03 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_BookStore', '0006_soldbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 3, 23, 0, 28, 453215)),
        ),
    ]
